### ISSUE TITLE
Support for IJulia

### ISSUE THREAD

**Issue by diegozea** [Evizero/UnicodePlots.jl#9] opened 2015-08-19 13:38 UTC
¡Hi! At the moment, IJulia show the plots in the following way:

![ijulia](https://cloud.githubusercontent.com/assets/2822757/9357636/7943adfa-465e-11e5-8f82-10ecfeb963e5.png)

**Comment by Evizero** [comment] 2015-08-19 13:41
Not much I can do about that I think. The missing newline should be corrected in the current master, but the weird line stretching is due to the fact that the monospace font that your IJulia uses is not as monospace as it pretends to be

**Comment by Evizero** [comment] 2015-08-19 13:43
- [ ] but i will look into it a little closer. didn't really use IJulia yet

**Comment by Evizero** [comment] 2015-08-20 07:39
do the line-breaks now work for you? (don't forget Pkg.update())

**Comment by Evizero** [comment] 2015-08-21 14:28
Thank you for the report. This should be fixed now, so I am closing this issue.

The uneven line spacing issue in IJulia is due to the font that pretends to be monospace but really isn't. However, if you set `border=:dotted` it will look a lot less ugly.

![ijulia](https://cloud.githubusercontent.com/assets/10854026/9410470/becc8ad6-4820-11e5-86fd-ded88a850d82.png)

**Closed** 2015-08-21 14:29 UTC
Labels: compatibility

**Comment by diegozea** [comment] 2015-08-21 16:43
Great, thanks! :)

**Comment by stevengj** [comment] 2019-01-19 20:51
Regarding the font-spacing problem, can you give more detail?  It would be nice to file a bug report with Jupyter if this is the case.

(Of course, even in a monospace font, fonts and displays don't always agree about which glyphs are width 2 and which are width 1.)

**Comment by stevengj** [comment] 2019-01-19 20:57
Oh I see, the problem is the Braille characters?  For example, the exclamation marks don't line up for `println("a!\n⢀!\n")`

**Comment by Evizero** [comment] 2019-01-19 21:01
Right. it seems the braille character set is treated very differently from one font to the next

**Comment by stevengj** [comment] 2019-01-19 21:11
I filed a Jupyter bug.  Even if it is falling back to a non-monospaced font for the glyph of some Unicode character, it should still emulate a Terminal by using a layout grid based on the original monospace font.

**Comment by Evizero** [comment] 2019-01-19 21:15
thank you

**Comment by t-bltg** [comment] 2021-09-08 14:45
For reference: https://github.com/JuliaPlots/UnicodePlots.jl#know-issues.
