### ISSUE TITLE
InexactError() when plotting

### ISSUE THREAD

**Issue by lopezm94** [Evizero/UnicodePlots.jl#51] opened 2016-07-31 10:43 UTC
When trying to plot `Array{Float64, N}`, sometimes I get the following error:

```julia
ERROR: InexactError()
 in Plot at /home/USER/.julia/v0.4/UnicodePlots/src/plot.jl:151
```

*There are no NaN or Inf values*

**Comment by Evizero** [comment] 2016-07-31 11:42
can you give me a little more details? What was the command your executed, and what were your trying to do? What is `N` in your case?

**Comment by lopezm94** [comment] 2016-07-31 12:06
It happens with N in [1,2] (but mostly 2), the calls are almost identical, here is the matrix case:

```julia
julia> plot = scatterplot([left],[miny],xlim=[left,iters],ylim=[miny,maxy],title=title,name=name)
ERROR: InexactError()
 in Plot at /home/juan/.julia/v0.4/UnicodePlots/src/plot.jl:150

#Variale (name, type, value)
left Int64 1
iters Int64 34
miny Float64 -0.8794276565174709
maxy Float64 1.2796649117521434e218
title ASCIIString 
```

I see this tends to happen when the difference between miny and maxy is big

**Comment by Evizero** [comment] 2016-07-31 12:24
I can reproduce this. I shall investigate

**Comment by Evizero** [comment] 2016-07-31 12:29
The "issue" is with `round`. It is caused because I try to convert floats that are integers (like 1.0) into integers so that the axis labels are a little less noisy. In this case though the number is too big to be stored as an Int64 which causes the `InexactError`.

**Comment by Evizero** [comment] 2016-07-31 12:35
I think it should be fixed by replacing the four

```julia
min_y_str = string(isinteger(min_y) ? round(Int, min_y, RoundNearestTiesUp) : min_y)
```

lines at https://github.com/Evizero/UnicodePlots.jl/blob/master/src/plot.jl#L148-L151 with a bounds check

```julia
min_y_str = string((isinteger(min_y) &&  typemin(Int) < min_y < typemax(Int)) ? round(Int, min_y, RoundNearestTiesUp) : min_y)
```

I can't fix it right now but I shall do it in the next few days. If you want you could also submit a PR with these changes

**Closed** 2016-08-01 01:11 UTC
Labels: bug
